{
 "title": "Londinium",
 "time": { "from": "2018-01-29T07:00:00.000Z", "to": "2018-01-29T18:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "status",
    "label": "Status",
    "query": "DNA,Cancelled,Booked,Available,Attended"
   },
   {
    "name": "bookingtype",
    "label": "BookingType",
    "query": "Practice,EMIS Access,EMIS Mobile,External Organisation,Patient Schedule,NULL"
   },
   {
    "name": "cdb",
    "label": "CDB",
    "query": "select distinct cdb from appointment_stat where cdb IS NOT NULL order by cdb"
   }
  ]
 },
 "panels": [
  { "title": "Statistical Map Spread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Area Data Points ($status + $bookingtype)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 22, "x": 0, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \n\t$__timeGroup(log_date, '5m') as time,\n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = '$status'\nAND method in ($bookingtype)\nGROUP BY time, cdb\norder by log_date desc;\n"
    }
   ]
  },
  {
   "title": "Attended",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Attended'"
    }
   ]
  },
  {
   "title": "DNA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'DNA'"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Available'"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Cancelled'"
    }
   ]
  },
  {
   "title": "Estate Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attended",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\t  $__timeGroup(log_date,'5m') as time,\n\t  'Attended' as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Attended'\nGROUP BY time\norder by time;"
      }
     ]
    },
    {
     "title": "Cancelled",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\t  $__timeGroup(log_date,'5m') as time,\n\t  'Cancelled' as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Cancelled'\nGROUP BY time\norder by time;\n\n\n\n\n"
      }
     ]
    },
    {
     "title": "Did Not Attend",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\t  $__timeGroup(log_date,'5m') as time,\n\t  'DidNotAttend' as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'DNA'\nGROUP BY time\norder by time;"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n\t  $__timeGroup(log_date,'5m') as time,\n\t  'Available' as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Available'\nGROUP BY time\norder by time;"
      }
     ]
    }
   ]
  },
  { "title": "CDB Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Attended ($cdb)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\tUNIX_TIMESTAMP(date_format( log_date, '%Y-%m-%d %H:%i:00' )) as time_sec,\n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Attended'\nAND cdb in ($cdb)\nGROUP BY time_sec, cdb\norder by log_date desc;"
    }
   ]
  },
  {
   "title": "Cancelled ($cdb)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\tUNIX_TIMESTAMP(date_format( log_date, '%Y-%m-%d %H:%i:00' )) as time_sec,\n        cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Cancelled'\nAND cdb in ($cdb)\nGROUP BY time_sec, cdb\norder by log_date desc;"
    }
   ]
  },
  {
   "title": "Did Not Attend ($cdb)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\tUNIX_TIMESTAMP(date_format( log_date, '%Y-%m-%d %H:%i:00' )) as time_sec,\n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'DNA'\nAND cdb in ($cdb)\nGROUP BY time_sec, cdb\norder by log_date desc;"
    }
   ]
  },
  {
   "title": "Available ($cdb)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\tUNIX_TIMESTAMP(date_format( log_date, '%Y-%m-%d %H:%i:00' )) as time_sec,\n    cdb as metric,\n    sum( value ) as value\nFROM  appointment_stat \nWHERE $__timeFilter(log_date)\nAND status = 'Available'\nAND cdb in ($cdb)\nGROUP BY time_sec, cdb\norder by log_date desc;"
    }
   ]
  }
 ]
}